function searchPlayer() {
  const inputRaw = document.getElementById("playerInput").value.trim();
  if (inputRaw === "") {
    alert("선수 이름을 입력해주세요!");
    return;
  }

  const input = inputRaw.toLowerCase();

  // 별명 매핑용 (한글 or 별명 등)
  const aliasMap = {
    "플레타": "Fleta",
    "프로핏": "Profit",
    "카르페": "Carpe",
    "류제홍": "Ryujehong",
    "늙은이": "Ryujehong",
    "아나버림": "Ryujehong",
    "라위충": "Ryujehong",
    "쪼낙": "JJoNak",
    "퓨리": "Fury",
    "제스처": "Gesture",
    "프로비": "Probe",
    "프로퍼": "Proper",
    "랍": "Lip",
    "희상": "Heesang",
    "준빈": "JunBin",
    "맥스": "Max",
    "초롱": "CHORONG",
    "슈": "Shu",
    "나이프": "Knife",
    "에이리언": "A1IEN",
    "아벨": "ABEL",
    "에이비": "ABY",
    "에이스": "ACE",
    "아키": "AKI",
    "얼도우": "ALTHOGH",
    "올도우": "ALTHOUGH",
    "안순재": "ANSOONJAE",
    "아롱": "ARONG",
    "에티튜드": "ATTITUDE",
    "에이젠트": "Azent",
    "에이드": "Ade",
    "아도": "Ado",
    "어도라": "Adora",
    "에스테": "Aester",
    "에거서": "Agatha",
    "아가타": "Agatha",
    "애그니스": "Agnes",
    "에이든": "Aiden",
    "에임갓": "AimGod",
    "알밤": "AlBam",
    "알람": "Alarm",
    "에일리아": "Alia",
    "알파": "Alpha",
    "알파이": "AlphaYi",
    "어나덜": "Another",
    "아이온": "Ap3ach",
    "아퀼라": "Aquila",
    "아크": "Ark",
    "아란테": "Arcance",
    "아키텍쳐": "Architect",
    "알간": "Argon",
    "에리얼": "Ariel",
    "얼라이즈": "Arise",
    "어로스": "Aros",
    "어라운드": "Around",
    "얼로우": "Arrow",
    "야셀": "Asher",
    "아사신": "Assassin",
    "아스트리드": "Astrid",
    "어택": "Attack",
    "어툰": "Attune",
    "어와치": "AweWatch",
    "액시움": "Axxiom",
    "아이어나미": "Ayanami",
    "아즈탁": "Aztac",
    "백신": "BACKSIN",
    "벌린": "BERL1N",
    "벨린": "BERL1N",
    "베르나르": "BERNAR",
    "블링크": "BL1NK",
    "블린크": "BL1NK",
    "블래더": "BLAD3R",
    "블레더": "BLAD3R",
    "블라더": "BLAD3R",
    "보노": "BONO",
    "비큐비": "BQB",
    "바벨": "Babel",
    "베벨": "Babel",
    "배벨": "Babel",
    "바빌": "Babel",
    "베빌": "Babel",
    "배빌": "Babel",
    "배찌": "Bazzi",
    "베찌": "Bazzi",
    "브도신": "Bdosin",
    "Be9": "Be9",
    "비이구": "Be9",
    "비이나인": "Be9",
    "베베": "BeBe",
    "배배": "BeBe",
    "배베": "BeBe",
    "베배": "BeBe",
    "비비": "BeBe",
    "배포 ":"BePo",
    "베포" : "BePo",
    "비포" : "BePo",
    "베키" : "Becky",
    "배키 ": "Becky",
    "밸로스레아": "Belosrea",
    "벨로스레아": "Belosrea",
    "밸로스래아": "Belosrea",
    "벨로스래아": "Belosrea",
    "비옴": "Beom",
    "베옴": "Beom",
    "블랙클로버": "BlackCl0ver",
    "블렉클로버": "BlackCl0ver",
    "블리스": "Bliss",
    "블리츠": "Blitz",
    "블릿츠": "Blitz",
    "블리쯔": "Blitz",
    "블릿쯔": "Blitz",
    "분조": "BoonJo",
    "브렉": "Brek",
    "브랙": "Brek",
    "브라이트": "Bright",
    "범퍼": "Bumper",
    "버니": "Bunny",
    "바이렘": "Byrem",
    "": "CARU",
    "": "CCJ",
    "": "CHAEWOORI",
    "": "CRESCENT",
    "": "Caffeine",
    "": "Cane",
    "": "Carpe",
    "": "Ceno",
    "": "Chamggae",
    "체크메이트": "Checkmate",
    "": "ChiYo",
    "": "ChoiHyoBin",
    "": "ChoiSehwan",
    "초로아": "Chroa",
    "": "ChunSam",
    "": "Clestyn",
    "클루저": "Closer",
    "클라우드": "cloud",
    "소마": "CoMa",
    "": "Ce0ng",
    "크레이지": "Crazy",
    "": "Creative",
    "": "Curious",
    "": "DODO",
    "동학": "DONGHAK",
    "": "D0nghun",
    "": "D4RT",
    "다코": "DACO",
    "다다": "DADA",
    "": "DAEGUN",
    "": "DD1NGKoNG",
    "": "DDing",
    "": "DOX",
    "": "DPS",
    "": "Dahim",
    "대일리": "Daily"
    };

  let resolvedPlayer;

  if (aliasMap[input]) {
    resolvedPlayer = aliasMap[input];
  } else {
    resolvedPlayer = inputRaw;
  }

  const encodedName = encodeURIComponent(resolvedPlayer.replace(/ /g, "_"));
  const url = `https://liquipedia.net/overwatch/${encodedName}`;
  window.open(url, "_blank");
}
